name: Update Daily LeetCode Challenge

on:
  schedule:
    - cron: "* * * * 1"
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Cache dependencies. From:
      # https://github.com/actions/cache/blob/master/examples.md#python---pip
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Generate Challenge
        run: |
          python3 --version
          python3 scripts/main.py
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXCLUDE_FORKED_REPOS: true

      # Commits all changed files to the repository
      - name: Commit to the repo
        run: |
          git config --global user.name "Andres Vivallo"
          git config --global user.email "avivallo@avivallo.github.io"
          git add .
          # "echo" returns true so the build succeeds, even if no changed files
          git commit -m 'Update generated files' || echo
          git push
